INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('1', '1');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('1', '2');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('2', '2');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('2', '1');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('3', '4');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('4', '2');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('4', '3');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('4', '4');
INSERT INTO accidents_rules(accident_id, rule_id) VALUES ('4', '5');